// supabase/studio/blocks/vue/registry/default/password-based-auth/nuxtjs/app/pages/auth/update-password.vue
<script setup lang="ts">
import UpdatePasswordForm from "@/components/update-password-form.vue"
</script>

<template>
  <div class="flex min-h-screen w-full items-center justify-center p-6 md:p-10">
    <div class="w-full max-w-sm">
      <UpdatePasswordForm />
    </div>
  </div>
</template>

// supabase/studio/apps/ui-library/app/example/password-based-auth/auth/update-password/page.tsx
import { UpdatePasswordForm } from '@/registry/default/blocks/password-based-auth-nextjs/components/update-password-form'

export default function Page() {
  return (
    <div className="flex min-h-svh w-full items-center justify-center p-6 md:p-10">
      <div className="w-full max-w-sm">
        <UpdatePasswordForm />
      </div>
    </div>
  )
}
