// supabase/studio/apps/docs/app/error.tsx
'use client'

import * as Sentry from '@sentry/nextjs'
import Link from 'next/link'
import { useEffect } from 'react'
import { Button } from 'ui'

const ErrorPage = ({ error }) => {
  useEffect(() => {
    Sentry.captureException(error)
  }, [error])

  return (
    <div className="h-[calc(100vh-var(--header-height))] w-full flex flex-col gap-8 p-8 items-center justify-center">
      <span className="text-center text-5xl text-foreground-lighter">
        Sorry, something went wrong
      </span>
      <div className="flex flex-row items-center gap-4">
        <Button asChild type="secondary" className="w-fit p-4 text-lg">
          <Link href="/">Return to homepage</Link>
        </Button>
        <Button type="secondary" className="w-fit p-4 text-lg" onClick={() => location.reload()}>
          Refresh page
        </Button>
      </div>
    </div>
  )
}

export default ErrorPage

// supabase/studio/blocks/vue/registry/default/social-auth/nuxtjs/app/pages/auth/error.vue
<script setup lang="ts">
import { useRoute } from "vue-router"
import { computed } from "vue"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

const route = useRoute()
const errorMessage = computed(() => route.query.error as string || null)
</script>

<template>
  <div class="flex min-h-screen w-full items-center justify-center p-6 md:p-10">
    <div class="w-full max-w-sm">
      <div class="flex flex-col gap-6">
        <Card>
          <CardHeader>
            <CardTitle class="text-2xl">Sorry, something went wrong.</CardTitle>
          </CardHeader>
          <CardContent>
            <p v-if="errorMessage" class="text-sm text-muted-foreground">
              Code error: {{ errorMessage }}
            </p>
            <p v-else class="text-sm text-muted-foreground">
              An unspecified error occurred.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  </div>
</template>
