// supabase/studio/blocks/vue/registry/default/components/ui/Label.vue
<script setup lang="ts">
import { cva, type VariantProps } from "class-variance-authority"
import { cn } from "../../lib/utils"

const labelVariants = cva(
  "text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
)

type LabelVariants = VariantProps<typeof labelVariants>

defineProps<{
  as?: string
  class?: string
}>()

const props = defineProps({
  as: { type: String, default: "label" },
  class: { type: String, default: "" },
})

const labelClass = cn(labelVariants(), props.class)
</script>

<template>
  <component :is="as" :class="labelClass">
    <slot />
  </component>
</template>

// open-agent-platform/apps/web/src/components/ui/label.tsx
import * as React from "react";
import * as LabelPrimitive from "@radix-ui/react-label";

import { cn } from "@/lib/utils";

function Label({
  className,
  ...props
}: React.ComponentProps<typeof LabelPrimitive.Root>) {
  return (
    <LabelPrimitive.Root
      data-slot="label"
      className={cn(
        "flex items-center gap-2 text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50",
        className,
      )}
      {...props}
    />
  );
}

export { Label };
