// supabase/studio/apps/ui-library/registry/default/blocks/password-based-auth-nextjs/app/auth/forgot-password/page.tsx
import { ForgotPasswordForm } from '@/registry/default/blocks/password-based-auth-nextjs/components/forgot-password-form'

export default function Page() {
  return (
    <div className="flex min-h-svh w-full items-center justify-center p-6 md:p-10">
      <div className="w-full max-w-sm">
        <ForgotPasswordForm />
      </div>
    </div>
  )
}

// supabase/studio/blocks/vue/registry/default/password-based-auth/nuxtjs/app/pages/auth/forgot-password.vue
<script setup lang="ts">
import ForgotPasswordForm from "@/components/forgot-password-form.vue"
</script>

<template>
  <div class="flex min-h-screen w-full items-center justify-center p-6 md:p-10">
    <div class="w-full max-w-sm">
      <ForgotPasswordForm />
    </div>
  </div>
</template>
